apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    dt.owner: "platform_team"
  name: kubeaudit
  namespace: argocd
spec:
  sources:
    - repoURL: "GITHUB_DOT_COM_REPO_PLACEHOLDER"
      targetRevision: main
      path: "gitops/manifests/platform/kubeaudit"
  destination:
    namespace: kubeaudit
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2