---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector
    app.kubernetes.io/name: opentelemetry-collector
spec:
  ports:
    - name: otlp # Default endpoint for otlp receiver (gRPC)
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: http # Default endpoint for otlp receiver (HTTP)
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: metrics # Default endpoint for metrics.
      port: 8889
      protocol: TCP
      targetPort: 8889
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  type: NodePort